import {
  HrAlert,
  HrButton,
  HrButtonGroup,
  HrCollapse,
  HrCollapseItem,
  HrDropdown,
  HrDropdownItem,
  HrForm,
  HrFormItem,
  HrIcon,
  HrInput,
  HrLoading,
  HrMessage,
  HrMessageBox,
  HrNotification,
  HrOption,
  HrPopconfirm,
  HrSelect,
  HrSwitch,
  HrTooltip,
} from "@hr-element/components";
import type { Plugin } from "vue";

export default [
  HrButton,
  HrButtonGroup,
  HrIcon,
  HrCollapse,
  HrCollapseItem,
  HrAlert,
  HrTooltip,
  HrDropdown,
  HrDropdownItem,
  HrPopconfirm,
  HrMessage,
  HrNotification,
  HrMessageBox,
  HrInput,
  HrLoading,
  HrSwitch,
  HrSelect,
  HrOption,
  HrForm,
  HrFormItem,
] as Plugin[];
